package org.example;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

public class Day6Test {
    @Test
    public void testTerminates() {
        var input = """
                ....#.....
                .........#
                ..........
                ..#.......
                .......#..
                ..........
                .#..^.....
                ........#.
                #.........
                ......#...
                """;
        assertTrue(() -> Day6.terminates(Day6.parse(input)));
    }

    @Test
    public void testDoesNotTerminate() {
        var input = """
                ....#.....
                .........#
                ..........
                ..#.......
                .......#..
                ..........
                .#.O^.....
                ........#.
                #.........
                ......#...
                """;
        assertTrue(() -> Day6.terminates(Day6.parse(input)));
    }
}
